<?php
	// Hopefully the below HTML will be generated by database results
	// For now, just testing the thing will work

	echo '<ul data-role="listview" data-theme="g">
			<li>Beach 1</li>
			<li>Beach 2</li>
			<li>Beach 3</li>
			<li>Beach 4</li>
			<li>Beach 5</li>
		  </ul>';
?>